from ..models import (
    CPEProfile,
    DeviceCapabilityProfile,
    DeviceIdentityProfile,
    DiagnosticCapabilityProfile,
    TelemetryMetricProfile,
    WiFiBandProfile,
)

IGD = "InternetGatewayDevice"
PPP = (
    "InternetGatewayDevice.WANDevice.1."
    "WANConnectionDevice.4.WANPPPConnection.1"
)

RUNTIME_TTL = 900
CONFIG_TTL = 86400
STATIC_TTL = 604800

PROFILE = CPEProfile(
    vendor="TP-Link",
    product_class="XC220-G3v",
    data_model="TR-098",
    refresh_root=IGD,
    identity=DeviceIdentityProfile(
        model="XC220-G3v",
        family="XC Series",
        category="FTTH GPON Gateway",
        description="Dual-band GPON residential gateway qualified for Proximity Device360.",
        image="/devices/tplink-xc220-g3v.png",
    ),
    telemetry=(
        TelemetryMetricProfile(
            code="system.uptime_seconds",
            paths=(f"{IGD}.DeviceInfo.UpTime",),
            value_type="integer",
            unit="seconds",
            support="SUPPORTED",
            description="CPE uptime since the last reboot.",
            stale_after_seconds=RUNTIME_TTL,
            metadata={"freshness_class": "RUNTIME", "refresh_root": f"{IGD}.DeviceInfo"},
        ),
        TelemetryMetricProfile(
            code="system.cpu_usage_percent",
            support="UNSUPPORTED",
            unit="percent",
            reason="Qualified firmware does not expose CPU telemetry through ACS.",
            metadata={"freshness_class": "UNSUPPORTED"},
        ),
        TelemetryMetricProfile(
            code="system.memory_free_percent",
            support="UNSUPPORTED",
            unit="percent",
            reason="Qualified firmware does not expose MemoryStatus through ACS.",
            metadata={"freshness_class": "UNSUPPORTED"},
        ),
        TelemetryMetricProfile(
            code="system.memory_used_percent",
            support="UNSUPPORTED",
            unit="percent",
            reason="Qualified firmware does not expose MemoryStatus through ACS.",
            metadata={"freshness_class": "UNSUPPORTED"},
        ),
        TelemetryMetricProfile(
            code="wan.ppp.status",
            paths=(f"{PPP}.ConnectionStatus",),
            stale_after_seconds=RUNTIME_TTL,
            metadata={"freshness_class": "RUNTIME", "refresh_root": PPP},
        ),
        TelemetryMetricProfile(
            code="wan.ppp.ip_address",
            paths=(f"{PPP}.ExternalIPAddress",),
            stale_after_seconds=RUNTIME_TTL,
            metadata={"freshness_class": "RUNTIME", "refresh_root": PPP},
        ),
        TelemetryMetricProfile(
            code="wan.ppp.gateway",
            paths=(f"{PPP}.DefaultGateway",),
            stale_after_seconds=CONFIG_TTL,
            metadata={"freshness_class": "CONFIGURATION", "refresh_root": PPP},
        ),
        TelemetryMetricProfile(
            code="wan.ppp.username",
            paths=(f"{PPP}.Username",),
            stale_after_seconds=CONFIG_TTL,
            metadata={"freshness_class": "CONFIGURATION", "refresh_root": PPP},
        ),
        TelemetryMetricProfile(
            code="wan.ppp.uptime_seconds",
            paths=(f"{PPP}.Uptime",),
            value_type="integer",
            unit="seconds",
            stale_after_seconds=RUNTIME_TTL,
            metadata={"freshness_class": "RUNTIME", "refresh_root": PPP},
        ),
        TelemetryMetricProfile(
            code="wan.ppp.last_error",
            paths=(f"{PPP}.LastConnectionError",),
            stale_after_seconds=RUNTIME_TTL,
            metadata={"freshness_class": "RUNTIME", "refresh_root": PPP},
        ),
        TelemetryMetricProfile(
            code="wan.ppp.service_name",
            paths=(f"{PPP}.PPPoEServiceName",),
            stale_after_seconds=CONFIG_TTL,
            metadata={"freshness_class": "CONFIGURATION", "refresh_root": PPP},
        ),
        TelemetryMetricProfile(
            code="wan.ppp.dns_servers",
            paths=(f"{PPP}.DNSServers",),
            stale_after_seconds=CONFIG_TTL,
            metadata={"freshness_class": "CONFIGURATION", "refresh_root": PPP},
        ),
        TelemetryMetricProfile(
            code="wan.ppp.vlan",
            paths=(f"{PPP}.X_HW_VLAN",),
            value_type="integer",
            stale_after_seconds=STATIC_TTL,
            metadata={"freshness_class": "STATIC", "refresh_root": PPP},
        ),
        TelemetryMetricProfile(
            code="firmware.software_version",
            paths=(f"{IGD}.DeviceInfo.SoftwareVersion",),
            stale_after_seconds=STATIC_TTL,
            metadata={"freshness_class": "STATIC", "refresh_root": f"{IGD}.DeviceInfo"},
        ),
        TelemetryMetricProfile(
            code="firmware.hardware_version",
            paths=(f"{IGD}.DeviceInfo.HardwareVersion",),
            stale_after_seconds=STATIC_TTL,
            metadata={"freshness_class": "STATIC", "refresh_root": f"{IGD}.DeviceInfo"},
        ),
    ),
    capabilities=(
        DeviceCapabilityProfile(
            code="system.cpu.telemetry",
            support="UNSUPPORTED",
            qualification="QUALIFIED",
            reason="CPU usage is not exported by the qualified firmware.",
        ),
        DeviceCapabilityProfile(
            code="system.memory.telemetry",
            support="UNSUPPORTED",
            qualification="QUALIFIED",
            reason="MemoryStatus is not exported by the qualified firmware.",
        ),
        DeviceCapabilityProfile(
            code="wan.ppp.telemetry",
            support="SUPPORTED",
            qualification="QUALIFIED",
        ),
        DeviceCapabilityProfile(
            code="wifi.configuration",
            support="SUPPORTED",
            qualification="QUALIFIED",
        ),
        DeviceCapabilityProfile(
            code="wifi.scan.execute",
            support="SUPPORTED",
            qualification="QUALIFIED",
        ),
        DeviceCapabilityProfile(
            code="wifi.scan.results_exported",
            support="LIMITED",
            qualification="QUALIFIED",
            reason="The scan completes but X_TP_BSSDescEntry rows are not exported through ACS.",
        ),
    ),
    diagnostics=(
        DiagnosticCapabilityProfile(
            code="PING",
            aliases=("PING", "IP_PING", "PING_DIAGNOSTIC"),
            support="SUPPORTED",
            qualification="QUALIFIED",
            execution="DEVICE_DIAGNOSTICS_ENGINE",
            timeout_seconds=60,
            metadata={"evidence": "EUREKA26.0.0 Active Ping Foundation", "hub_executable": True, "execution_note": "Ping eseguito dal Diagnostics Hub tramite adapter Active Ping."},
        ),
        DiagnosticCapabilityProfile(
            code="TRACEROUTE",
            aliases=("TRACEROUTE", "TRACE_ROUTE"),
            support="NOT_QUALIFIED",
            qualification="NOT_QUALIFIED",
            reason="Real-device execution has not been qualified on XC220-G3v.",
            timeout_seconds=120,
        ),
        DiagnosticCapabilityProfile(
            code="DNS_LOOKUP",
            aliases=("DNS_LOOKUP", "DNS_TEST", "DNS"),
            support="NOT_QUALIFIED",
            qualification="NOT_QUALIFIED",
            reason="DNS diagnostics have not been qualified on XC220-G3v.",
            timeout_seconds=60,
        ),
        DiagnosticCapabilityProfile(
            code="DOWNLOAD_DIAGNOSTIC",
            aliases=("DOWNLOAD_DIAGNOSTIC", "TR143_DOWNLOAD", "DOWNLOAD"),
            support="LIMITED",
            qualification="DISCOVERED",
            execution="DEVICE_DIAGNOSTICS_ENGINE",
            reason="TR-143 DownloadDiagnostics disponibile tramite adapter legacy; validazione finale in corso.",
            timeout_seconds=300,
            metadata={"hub_executable": True, "adapter": "LEGACY_TR143_DOWNLOAD"},
        ),
        DiagnosticCapabilityProfile(
            code="TR143_SPEEDTEST",
            aliases=("TR143_SPEEDTEST", "SPEEDTEST"),
            support="LIMITED",
            qualification="DISCOVERED",
            execution="DEVICE_DIAGNOSTICS_ENGINE",
            reason="Speed test carrier disponibile in modalità download TR-143; upload non ancora qualificato.",
            timeout_seconds=300,
            metadata={"hub_executable": True, "adapter": "LEGACY_TR143_DOWNLOAD", "mode": "DOWNLOAD_ONLY"},
        ),
        DiagnosticCapabilityProfile(
            code="UPLOAD_DIAGNOSTIC",
            aliases=("UPLOAD_DIAGNOSTIC", "TR143_UPLOAD", "UPLOAD"),
            support="LIMITED",
            qualification="DISCOVERED",
            execution=None,
            reason="TR-143 object discovered; real-device execution still requires qualification.",
            timeout_seconds=300,
        ),
        DiagnosticCapabilityProfile(
            code="WIFI_SCAN",
            aliases=("WIFI_SCAN",),
            support="SUPPORTED",
            qualification="QUALIFIED",
            execution="DEVICE_DIAGNOSTICS_ENGINE",
            reason="Scan execution qualified; neighbor result export is limited by firmware.",
            timeout_seconds=90,
            metadata={"results_export": "LIMITED", "hub_executable": True},
        ),
        DiagnosticCapabilityProfile(
            code="FOUNDATION_PROBE",
            aliases=("FOUNDATION_PROBE",),
            support="SUPPORTED",
            qualification="PLATFORM",
            execution="DEVICE_DIAGNOSTICS_ENGINE",
            timeout_seconds=30,
            metadata={"technical": True, "hub_executable": True},
        ),
    ),
    metadata={
        "qualified_firmware": [
            "1.8.0 0.8.0 v6062.0 Build 230720 Rel.48094n",
        ],
        "release": "EUREKA36.3.0",
        "freshness_policy": {
            "RUNTIME": RUNTIME_TTL,
            "CONFIGURATION": CONFIG_TTL,
            "STATIC": STATIC_TTL,
        },
    },
    wifi24=WiFiBandProfile(
        ssid=f"{IGD}.LANDevice.1.WLANConfiguration.1.SSID",
        password=f"{IGD}.LANDevice.1.WLANConfiguration.1.PreSharedKey.1.KeyPassphrase",
        enable=f"{IGD}.LANDevice.1.WLANConfiguration.1.Enable",
        channel=f"{IGD}.LANDevice.1.WLANConfiguration.1.Channel",
        auto_channel=f"{IGD}.LANDevice.1.WLANConfiguration.1.AutoChannelEnable",
        bandwidth=f"{IGD}.LANDevice.1.WLANConfiguration.1.X_TP_Bandwidth",
        radio_enabled=f"{IGD}.LANDevice.1.WLANConfiguration.1.RadioEnabled",
        ssid_advertisement_enabled=f"{IGD}.LANDevice.1.WLANConfiguration.1.SSIDAdvertisementEnabled",
        transmit_power=f"{IGD}.LANDevice.1.WLANConfiguration.1.TransmitPower",
        wps_enable=f"{IGD}.LANDevice.1.WLANConfiguration.1.WPS.Enable",
        beacon_type=f"{IGD}.LANDevice.1.WLANConfiguration.1.BeaconType",
        wpa_authentication_mode=f"{IGD}.LANDevice.1.WLANConfiguration.1.WPAAuthenticationMode",
        ieee11i_authentication_mode=f"{IGD}.LANDevice.1.WLANConfiguration.1.IEEE11iAuthenticationMode",
        wpa_encryption_modes=f"{IGD}.LANDevice.1.WLANConfiguration.1.WPAEncryptionModes",
        ieee11i_encryption_modes=f"{IGD}.LANDevice.1.WLANConfiguration.1.IEEE11iEncryptionModes",
        standard=f"{IGD}.LANDevice.1.WLANConfiguration.1.Standard",
        max_bit_rate=f"{IGD}.LANDevice.1.WLANConfiguration.1.MaxBitRate",
        neighbor_scan_trigger=f"{IGD}.LANDevice.1.WLANConfiguration.1.X_TP_NeighbourScanEnabled",
        neighbor_scan_trigger_value="Requested",
        neighbor_scan_results=f"{IGD}.LANDevice.1.WLANConfiguration.1.X_TP_BSSDescEntry",
    ),
    wifi5=WiFiBandProfile(
        ssid=f"{IGD}.LANDevice.1.WLANConfiguration.3.SSID",
        password=f"{IGD}.LANDevice.1.WLANConfiguration.3.PreSharedKey.1.KeyPassphrase",
        enable=f"{IGD}.LANDevice.1.WLANConfiguration.3.Enable",
        channel=f"{IGD}.LANDevice.1.WLANConfiguration.3.Channel",
        auto_channel=f"{IGD}.LANDevice.1.WLANConfiguration.3.AutoChannelEnable",
        bandwidth=f"{IGD}.LANDevice.1.WLANConfiguration.3.X_TP_Bandwidth",
        radio_enabled=f"{IGD}.LANDevice.1.WLANConfiguration.3.RadioEnabled",
        ssid_advertisement_enabled=f"{IGD}.LANDevice.1.WLANConfiguration.3.SSIDAdvertisementEnabled",
        transmit_power=f"{IGD}.LANDevice.1.WLANConfiguration.3.TransmitPower",
        wps_enable=f"{IGD}.LANDevice.1.WLANConfiguration.3.WPS.Enable",
        beacon_type=f"{IGD}.LANDevice.1.WLANConfiguration.3.BeaconType",
        wpa_authentication_mode=f"{IGD}.LANDevice.1.WLANConfiguration.3.WPAAuthenticationMode",
        ieee11i_authentication_mode=f"{IGD}.LANDevice.1.WLANConfiguration.3.IEEE11iAuthenticationMode",
        wpa_encryption_modes=f"{IGD}.LANDevice.1.WLANConfiguration.3.WPAEncryptionModes",
        ieee11i_encryption_modes=f"{IGD}.LANDevice.1.WLANConfiguration.3.IEEE11iEncryptionModes",
        standard=f"{IGD}.LANDevice.1.WLANConfiguration.3.Standard",
        max_bit_rate=f"{IGD}.LANDevice.1.WLANConfiguration.3.MaxBitRate",
        neighbor_scan_trigger=f"{IGD}.LANDevice.1.WLANConfiguration.3.X_TP_NeighbourScanEnabled",
        neighbor_scan_trigger_value="Requested",
        neighbor_scan_results=f"{IGD}.LANDevice.1.WLANConfiguration.3.X_TP_BSSDescEntry",
    ),
)
