from .router_replacement import ROUTER_REPLACEMENT_WORKFLOW
from .first_service_provisioning import FIRST_SERVICE_PROVISIONING_WORKFLOW


WORKFLOW_DEFINITIONS = {
    "ROUTER_REPLACEMENT": ROUTER_REPLACEMENT_WORKFLOW,
    "FIRST_SERVICE_PROVISIONING": FIRST_SERVICE_PROVISIONING_WORKFLOW,
}
