"""EUREKA6.0.0.4 customer correlation foundation

Revision ID: 31826d45d53b
Revises: 683a94cadf9f
Create Date: 2026-06-07 12:46:54.082659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31826d45d53b'
down_revision: Union[str, Sequence[str], None] = '683a94cadf9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('customer_name', sa.String(length=255), nullable=True))
    op.add_column('devices', sa.Column('service_code', sa.String(length=64), nullable=True))
    op.add_column('devices', sa.Column('service_order_code', sa.String(length=64), nullable=True))
    op.add_column('devices', sa.Column('site_address', sa.String(length=255), nullable=True))
    op.alter_column('devices', 'customer_code',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.create_index(op.f('ix_devices_service_code'), 'devices', ['service_code'], unique=False)
    op.create_index(op.f('ix_devices_service_order_code'), 'devices', ['service_order_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_service_order_code'), table_name='devices')
    op.drop_index(op.f('ix_devices_service_code'), table_name='devices')
    op.alter_column('devices', 'customer_code',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.drop_column('devices', 'site_address')
    op.drop_column('devices', 'service_order_code')
    op.drop_column('devices', 'service_code')
    op.drop_column('devices', 'customer_name')
    # ### end Alembic commands ###
