"""EUREKA6.0.0.3 proximity core data model

Revision ID: 683a94cadf9f
Revises: 
Create Date: 2026-06-07 09:56:05.350226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '683a94cadf9f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_code', sa.String(length=64), nullable=False),
    sa.Column('acs_device_id', sa.Text(), nullable=False),
    sa.Column('serial_number', sa.String(length=128), nullable=True),
    sa.Column('oui', sa.String(length=32), nullable=True),
    sa.Column('manufacturer', sa.String(length=128), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('product_class', sa.String(length=128), nullable=True),
    sa.Column('software_version', sa.String(length=128), nullable=True),
    sa.Column('hardware_version', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('online', sa.Boolean(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acs_last_inform', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('customer_code', sa.String(length=128), nullable=True),
    sa.Column('raw_acs_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('acs_device_id'),
    sa.UniqueConstraint('device_code')
    )
    op.create_index(op.f('ix_devices_customer_code'), 'devices', ['customer_code'], unique=False)
    op.create_index(op.f('ix_devices_oui'), 'devices', ['oui'], unique=False)
    op.create_index(op.f('ix_devices_serial_number'), 'devices', ['serial_number'], unique=False)
    op.create_index(op.f('ix_devices_tenant_id'), 'devices', ['tenant_id'], unique=False)
    op.create_table('device_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_events_device_id'), 'device_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_events_event_type'), 'device_events', ['event_type'], unique=False)
    op.create_table('device_parameters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('parameter_name', sa.Text(), nullable=False),
    sa.Column('parameter_value', sa.Text(), nullable=True),
    sa.Column('parameter_type', sa.String(length=64), nullable=True),
    sa.Column('last_refresh', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_parameters_device_id'), 'device_parameters', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_parameters_parameter_name'), 'device_parameters', ['parameter_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_parameters_parameter_name'), table_name='device_parameters')
    op.drop_index(op.f('ix_device_parameters_device_id'), table_name='device_parameters')
    op.drop_table('device_parameters')
    op.drop_index(op.f('ix_device_events_event_type'), table_name='device_events')
    op.drop_index(op.f('ix_device_events_device_id'), table_name='device_events')
    op.drop_table('device_events')
    op.drop_index(op.f('ix_devices_tenant_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_serial_number'), table_name='devices')
    op.drop_index(op.f('ix_devices_oui'), table_name='devices')
    op.drop_index(op.f('ix_devices_customer_code'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
